
OBJS += $(OUT)/svc/misc/svc.o

RPCS += $(OUT)/svc/misc/rpc_srv.o

RPCL += $(OUT)/svc/misc/rpc_clnt.o

RPCH += $(SRC)/svc/misc/rpc.h

RPCC += $(SRC)/svc/misc/rpc_srv.c		 \
		$(SRC)/svc/misc/rpc_clnt.c       \
		$(SRC)/svc/misc/rpc_xlate.c

RPCHDR += $(SRC)/svc/misc/rpc_header.h

DIRS += $(OUT)/svc/misc

