
OBJS += $(OUT)/drivers/drc/fsl_drc.o
OBJS += $(OUT)/drivers/drc/fsl_drc_dqs2dq.o
OBJS += $(OUT)/drivers/drc/fsl_drc_cbt.o
OBJS += $(OUT)/drivers/drc/fsl_drc_derate.o
OBJS += $(OUT)/drivers/drc/fsl_drc_rdbi_deskew.o
OBJS += $(OUT)/drivers/drc/fsl_drc_dram_vref.o

DIRS += $(OUT)/drivers/drc

