/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing includes.
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/include_h.pl */

#ifndef SC_PLATFORM_CONFIG_MX8QM_ALL_SS_H
#define SC_PLATFORM_CONFIG_MX8QM_ALL_SS_H

/* Includes */

#include "ss/a53/v1/ss.h"
#include "ss/a72/v1/ss.h"
#include "ss/audio/v1/ss.h"
#include "ss/base/v1/ss.h"
#include "ss/cci/v1/ss.h"
#include "ss/conn/v1/ss.h"
#include "ss/csi/v1/ss.h"
#include "ss/db/v1/ss.h"
#include "ss/dblogic/v1/ss.h"
#include "ss/dc/v1/ss.h"
#include "ss/dma/v1/ss.h"
#include "ss/drc/v1/ss.h"
#include "ss/gpu/v1/ss.h"
#include "ss/hdmi/v1/ss.h"
#include "ss/hdmi_rx/v1/ss.h"
#include "ss/hsio/v1/ss.h"
#include "ss/img/v1/ss.h"
#include "ss/lsio/v2/ss.h"
#include "ss/lvds/v1/ss.h"
#include "ss/m4/v1/ss.h"
#include "ss/mipi/v1/ss.h"
#include "ss/sc/v2/ss.h"
#include "ss/vpu/v3/ss.h"

#endif /* SC_PLATFORM_CONFIG_MX8QM_ALL_SS_H */

