
OBJS += $(OUT)/drivers/analog/fsl_analog.o
OBJS += $(OUT)/drivers/analog/fsl_analog_refgen.o
OBJS += $(OUT)/drivers/analog/fsl_analog_bias.o
OBJS += $(OUT)/drivers/analog/fsl_analog_pll.o
OBJS += $(OUT)/drivers/analog/fsl_vdetect.o

DIRS += $(OUT)/drivers/analog

