
OBJS += $(OUT)/svc/timer/svc.o

RPCS += $(OUT)/svc/timer/rpc_srv.o

RPCL += $(OUT)/svc/timer/rpc_clnt.o

RPCH += $(SRC)/svc/timer/rpc.h

RPCC += $(SRC)/svc/timer/rpc_srv.c		 \
		$(SRC)/svc/timer/rpc_clnt.c      \
		$(SRC)/svc/timer/rpc_xlate.c

RPCHDR += $(SRC)/svc/timer/rpc_header.h

DIRS += $(OUT)/svc/timer

