/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the SC subsystem.
 *
 * @addtogroup SC_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/rsrc_ss_h.pl */

#ifndef SC_SS_SC_RSRC_H
#define SC_SS_SC_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/** @{ */
#define SS_R_SC_PID0             0U
#define SS_R_SC_PID1             1U
#define SS_R_SC_PID2             2U
#define SS_R_SC_PID3             3U
#define SS_R_SC_PID4             4U
#define SS_R_SC_SEMA42           5U
#define SS_R_SC_TPM              6U
#define SS_R_SC_PIT              7U
#define SS_R_SC_UART             8U
#define SS_R_SC_I2C              9U
#define SS_R_SC_MU_0B            10U
#define SS_R_SC_MU_0A0           11U
#define SS_R_SC_MU_0A1           12U
#define SS_R_SC_MU_0A2           13U
#define SS_R_SC_MU_0A3           14U
#define SS_R_SC_MU_1A            15U
#define SS_R_SYSCNT_RD           16U
#define SS_R_SYSCNT_CMP          17U
#define SS_R_DEBUG               18U
#define SS_R_SYSTEM              19U
#define SS_R_SECO                20U
#define SS_R_CAAM_JR1            21U
#define SS_R_CAAM_JR1_OUT        22U
#define SS_R_CAAM_JR2            23U
#define SS_R_CAAM_JR2_OUT        24U
#define SS_R_CAAM_JR3            25U
#define SS_R_CAAM_JR3_OUT        26U
#define SS_R_SECO_MU_2           27U
#define SS_R_SECO_MU_3           28U
#define SS_R_SECO_MU_4           29U
#define SS_R_OTP                 30U
#define SS_R_ATTESTATION         31U
#define SS_R_SECVIO              32U
/** @} */

#endif /* SC_SS_SC_RSRC_H */

/** @} */

