
OBJS += $(OUT)/ss/vpu/v4/ss.o

CONFIGH += $(SRC)/ss/vpu/v4/config.h $(SRC)/ss/vpu/v4/rsrc.h

RSRC_MD += $(SRC)/ss/vpu/v4/resource.txt

CLK_MD += $(SRC)/ss/vpu/v4/clock.txt

CTRL_MD += $(SRC)/ss/vpu/v4/control.txt

DIRS += $(OUT)/ss/vpu/v4

