
OBJS += $(OUT)/svc/irq/svc.o

RPCS += $(OUT)/svc/irq/rpc_srv.o

RPCL += $(OUT)/svc/irq/rpc_clnt.o

RPCH += $(SRC)/svc/irq/rpc.h

RPCC += $(SRC)/svc/irq/rpc_srv.c		\
		$(SRC)/svc/irq/rpc_clnt.c       \
		$(SRC)/svc/irq/rpc_xlate.c

RPCHDR += $(SRC)/svc/irq/rpc_header.h

DIRS += $(OUT)/svc/irq

