
OBJS += $(OUT)/svc/pm/svc.o

RPCS += $(OUT)/svc/pm/rpc_srv.o

RPCL += $(OUT)/svc/pm/rpc_clnt.o

RPCH += $(SRC)/svc/pm/rpc.h

RPCC += $(SRC)/svc/pm/rpc_srv.c		 \
		$(SRC)/svc/pm/rpc_clnt.c     \
		$(SRC)/svc/pm/rpc_xlate.c

RPCHDR += $(SRC)/svc/pm/rpc_header.h

DIRS += $(OUT)/svc/pm

