/*
** ###################################################################
**
**     Copyright 2019-2020 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

#ifndef IOMUXD_H
#define IOMUXD_H


#ifndef IOMUXD_REG_BASE
  #ifdef  SCU_RESOURCES
    #define IOMUXD_REG_BASE 0x41F80000U
  #else
    #define IOMUXD_REG_BASE 0x33F80000U
  #endif
#endif

                                                                                   //  NUM RING GROUP PAD |  0                                        | 1                                        | 2                                        | 3                                        | 4                                        | 5                                        | 6                                        | 7                                        |
#define IOMUXD__PCIE_CTRL0_PERST_B               REG32(IOMUXD_REG_BASE+0x00000000U) //    0    0     0   0 |  HSIO.PCIE0.PERST_B                       |                                          |                                          |                                          | LSIO.GPIO4.IO00                          | LSIO.GPIO7.IO00                          |                                          |                                          |                                          |
#define IOMUXD__PCIE_CTRL0_CLKREQ_B              REG32(IOMUXD_REG_BASE+0x00000040U) //    0    0     0   1 |  HSIO.PCIE0.CLKREQ_B                      |                                          |                                          |                                          | LSIO.GPIO4.IO01                          | LSIO.GPIO7.IO01                          |                                          |                                          |                                          |
#define IOMUXD__PCIE_CTRL0_WAKE_B                REG32(IOMUXD_REG_BASE+0x00000080U) //    0    0     0   2 |  HSIO.PCIE0.WAKE_B                        |                                          |                                          |                                          | LSIO.GPIO4.IO02                          | LSIO.GPIO7.IO02                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_PCIESEP REG32(IOMUXD_REG_BASE+0x000000C0U) //    0    0     0   3 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__USB_SS3_TC0                      REG32(IOMUXD_REG_BASE+0x00020000U) //    1    1     0   0 |  ADMA.I2C1.SCL                            | CONN.USB_OTG1.PWR                        | CONN.USB_OTG2.PWR                        |                                          | LSIO.GPIO4.IO03                          | LSIO.GPIO7.IO03                          |                                          |                                          |                                          |
#define IOMUXD__USB_SS3_TC1                      REG32(IOMUXD_REG_BASE+0x00020040U) //    1    1     0   1 |  ADMA.I2C1.SCL                            | CONN.USB_OTG2.PWR                        |                                          |                                          | LSIO.GPIO4.IO04                          | LSIO.GPIO7.IO04                          |                                          |                                          |                                          |
#define IOMUXD__USB_SS3_TC2                      REG32(IOMUXD_REG_BASE+0x00020080U) //    1    1     0   2 |  ADMA.I2C1.SDA                            | CONN.USB_OTG1.OC                         | CONN.USB_OTG2.OC                         |                                          | LSIO.GPIO4.IO05                          | LSIO.GPIO7.IO05                          |                                          |                                          |                                          |
#define IOMUXD__USB_SS3_TC3                      REG32(IOMUXD_REG_BASE+0x000200C0U) //    1    1     0   3 |  ADMA.I2C1.SDA                            | CONN.USB_OTG2.OC                         |                                          |                                          | LSIO.GPIO4.IO06                          | LSIO.GPIO7.IO06                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_3V3_USB3IO  REG32(IOMUXD_REG_BASE+0x00020100U) //    1    1     0   4 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_CLK                        REG32(IOMUXD_REG_BASE+0x00020140U) //    1    1     0   5 |  CONN.EMMC0.CLK                           | CONN.NAND.READY_B                        |                                          |                                          | LSIO.GPIO4.IO07                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_CMD                        REG32(IOMUXD_REG_BASE+0x00020180U) //    1    1     0   6 |  CONN.EMMC0.CMD                           | CONN.NAND.DQS                            |                                          |                                          | LSIO.GPIO4.IO08                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA0                      REG32(IOMUXD_REG_BASE+0x000201C0U) //    1    1     0   7 |  CONN.EMMC0.DATA0                         | CONN.NAND.DATA00                         |                                          |                                          | LSIO.GPIO4.IO09                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA1                      REG32(IOMUXD_REG_BASE+0x00020200U) //    1    1     0   8 |  CONN.EMMC0.DATA1                         | CONN.NAND.DATA01                         |                                          |                                          | LSIO.GPIO4.IO10                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA2                      REG32(IOMUXD_REG_BASE+0x00020240U) //    1    1     0   9 |  CONN.EMMC0.DATA2                         | CONN.NAND.DATA02                         |                                          |                                          | LSIO.GPIO4.IO11                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA3                      REG32(IOMUXD_REG_BASE+0x00020280U) //    1    1     0  10 |  CONN.EMMC0.DATA3                         | CONN.NAND.DATA03                         |                                          |                                          | LSIO.GPIO4.IO12                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA4                      REG32(IOMUXD_REG_BASE+0x000202C0U) //    1    1     0  11 |  CONN.EMMC0.DATA4                         | CONN.NAND.DATA04                         |                                          |                                          | LSIO.GPIO4.IO13                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA5                      REG32(IOMUXD_REG_BASE+0x00020300U) //    1    1     0  12 |  CONN.EMMC0.DATA5                         | CONN.NAND.DATA05                         |                                          |                                          | LSIO.GPIO4.IO14                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA6                      REG32(IOMUXD_REG_BASE+0x00020340U) //    1    1     0  13 |  CONN.EMMC0.DATA6                         | CONN.NAND.DATA06                         |                                          |                                          | LSIO.GPIO4.IO15                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_DATA7                      REG32(IOMUXD_REG_BASE+0x00020380U) //    1    1     0  14 |  CONN.EMMC0.DATA7                         | CONN.NAND.DATA07                         |                                          |                                          | LSIO.GPIO4.IO16                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_STROBE                     REG32(IOMUXD_REG_BASE+0x000203C0U) //    1    1     0  15 |  CONN.EMMC0.STROBE                        | CONN.NAND.CLE                            |                                          |                                          | LSIO.GPIO4.IO17                          |                                          |                                          |                                          |                                          |
#define IOMUXD__EMMC0_RESET_B                    REG32(IOMUXD_REG_BASE+0x00021000U) //    2    1     1   0 |  CONN.EMMC0.RESET_B                       | CONN.NAND.WP_B                           |                                          |                                          | LSIO.GPIO4.IO18                          |                                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_SD1FIX0 REG32(IOMUXD_REG_BASE+0x00021040U) //    2    1     1   1 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__USDHC1_RESET_B                   REG32(IOMUXD_REG_BASE+0x00021080U) //    2    1     1   2 |  CONN.USDHC1.RESET_B                      | CONN.NAND.RE_N                           | ADMA.SPI2.SCK                            | CONN.NAND.WE_B                           | LSIO.GPIO4.IO19                          | LSIO.GPIO7.IO08                          |                                          |                                          |                                          |
#define IOMUXD__USDHC1_VSELECT                   REG32(IOMUXD_REG_BASE+0x000210C0U) //    2    1     1   3 |  CONN.USDHC1.VSELECT                      | CONN.NAND.RE_P                           | ADMA.SPI2.SDO                            | CONN.NAND.RE_B                           | LSIO.GPIO4.IO20                          | LSIO.GPIO7.IO09                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_CTL_NAND_RE_P_N           REG32(IOMUXD_REG_BASE+0x00021100U) //    2    1     1   4 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__USDHC1_WP                        REG32(IOMUXD_REG_BASE+0x00021140U) //    2    1     1   5 |  CONN.USDHC1.WP                           | CONN.NAND.DQS_N                          | ADMA.SPI2.SDI                            | CONN.NAND.ALE                            | LSIO.GPIO4.IO21                          | LSIO.GPIO7.IO10                          |                                          |                                          |                                          |
#define IOMUXD__USDHC1_CD_B                      REG32(IOMUXD_REG_BASE+0x00021180U) //    2    1     1   6 |  CONN.USDHC1.CD_B                         | CONN.NAND.DQS_P                          | ADMA.SPI2.CS0                            | CONN.NAND.DQS                            | LSIO.GPIO4.IO22                          | LSIO.GPIO7.IO11                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_CTL_NAND_DQS_P_N          REG32(IOMUXD_REG_BASE+0x000211C0U) //    2    1     1   7 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_VSELSEP REG32(IOMUXD_REG_BASE+0x00021200U) //    2    1     1   8 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TXC                  REG32(IOMUXD_REG_BASE+0x00021240U) //    2    1     1   9 |  CONN.ENET0.RGMII_TXC                     | CONN.ENET0.RCLK50M_OUT                   | CONN.ENET0.RCLK50M_IN                    | CONN.NAND.CE1_B                          | LSIO.GPIO4.IO29                          | CONN.USDHC2.CLK                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TX_CTL               REG32(IOMUXD_REG_BASE+0x00021280U) //    2    1     1  10 |  CONN.ENET0.RGMII_TX_CTL                  |                                          |                                          | CONN.USDHC1.RESET_B                      | LSIO.GPIO4.IO30                          | CONN.USDHC2.CMD                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TXD0                 REG32(IOMUXD_REG_BASE+0x000212C0U) //    2    1     1  11 |  CONN.ENET0.RGMII_TXD0                    |                                          |                                          | CONN.USDHC1.VSELECT                      | LSIO.GPIO4.IO31                          | CONN.USDHC2.DATA0                        |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TXD1                 REG32(IOMUXD_REG_BASE+0x00021300U) //    2    1     1  12 |  CONN.ENET0.RGMII_TXD1                    |                                          |                                          | CONN.USDHC1.WP                           | LSIO.GPIO5.IO00                          | CONN.USDHC2.DATA1                        |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TXD2                 REG32(IOMUXD_REG_BASE+0x00021340U) //    2    1     1  13 |  CONN.ENET0.RGMII_TXD2                    |                                          | CONN.NAND.CE0_B                          | CONN.USDHC1.CD_B                         | LSIO.GPIO5.IO01                          | CONN.USDHC2.DATA2                        |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_TXD3                 REG32(IOMUXD_REG_BASE+0x00021380U) //    2    1     1  14 |  CONN.ENET0.RGMII_TXD3                    |                                          | CONN.NAND.RE_B                           |                                          | LSIO.GPIO5.IO02                          | CONN.USDHC2.DATA3                        |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_ENET_ENETB0 REG32(IOMUXD_REG_BASE+0x000213C0U) //    2    1     1  15 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RXC                  REG32(IOMUXD_REG_BASE+0x00022000U) //    3    1     2   0 |  CONN.ENET0.RGMII_RXC                     |                                          | CONN.NAND.WE_B                           | CONN.USDHC1.CLK                          | LSIO.GPIO5.IO03                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RX_CTL               REG32(IOMUXD_REG_BASE+0x00022040U) //    3    1     2   1 |  CONN.ENET0.RGMII_RX_CTL                  |                                          |                                          | CONN.USDHC1.CMD                          | LSIO.GPIO5.IO04                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RXD0                 REG32(IOMUXD_REG_BASE+0x00022080U) //    3    1     2   2 |  CONN.ENET0.RGMII_RXD0                    |                                          |                                          | CONN.USDHC1.DATA0                        | LSIO.GPIO5.IO05                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RXD1                 REG32(IOMUXD_REG_BASE+0x000220C0U) //    3    1     2   3 |  CONN.ENET0.RGMII_RXD1                    |                                          |                                          | CONN.USDHC1.DATA1                        | LSIO.GPIO5.IO06                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RXD2                 REG32(IOMUXD_REG_BASE+0x00022100U) //    3    1     2   4 |  CONN.ENET0.RGMII_RXD2                    | CONN.ENET0.RMII_RX_ER                    |                                          | CONN.USDHC1.DATA2                        | LSIO.GPIO5.IO07                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_RGMII_RXD3                 REG32(IOMUXD_REG_BASE+0x00022140U) //    3    1     2   5 |  CONN.ENET0.RGMII_RXD3                    |                                          | CONN.NAND.ALE                            | CONN.USDHC1.DATA3                        | LSIO.GPIO5.IO08                          |                                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_ENET_ENETB1 REG32(IOMUXD_REG_BASE+0x00022180U) //    3    1     2   6 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_REFCLK_125M_25M            REG32(IOMUXD_REG_BASE+0x000221C0U) //    3    1     2   7 |  CONN.ENET0.REFCLK_125M_25M               | CONN.ENET0.PPS                           | CONN.EQOS.PPS_IN                         | CONN.EQOS.PPS_OUT                        | LSIO.GPIO5.IO09                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_MDIO                       REG32(IOMUXD_REG_BASE+0x00022200U) //    3    1     2   8 |  CONN.ENET0.MDIO                          | ADMA.I2C3.SDA                            | CONN.EQOS.MDIO                           |                                          | LSIO.GPIO5.IO10                          | LSIO.GPIO7.IO16                          |                                          |                                          |                                          |
#define IOMUXD__ENET0_MDC                        REG32(IOMUXD_REG_BASE+0x00022240U) //    3    1     2   9 |  CONN.ENET0.MDC                           | ADMA.I2C3.SCL                            | CONN.EQOS.MDC                            |                                          | LSIO.GPIO5.IO11                          | LSIO.GPIO7.IO17                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIOCT REG32(IOMUXD_REG_BASE+0x00022280U) //    3    1     2  10 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TXC                  REG32(IOMUXD_REG_BASE+0x00023000U) //    4    1     3   0 |  LSIO.GPIO0.IO00                          | CONN.EQOS.RCLK50M_OUT                    | ADMA.LCDIF.D00                           | CONN.EQOS.RGMII_TXC                      | CONN.EQOS.RCLK50M_IN                     |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TXD2                 REG32(IOMUXD_REG_BASE+0x00023040U) //    4    1     3   1 |                                           |                                          | ADMA.LCDIF.D01                           | CONN.EQOS.RGMII_TXD2                     | LSIO.GPIO0.IO01                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TX_CTL               REG32(IOMUXD_REG_BASE+0x00023080U) //    4    1     3   2 |                                           |                                          | ADMA.LCDIF.D02                           | CONN.EQOS.RGMII_TX_CTL                   | LSIO.GPIO0.IO02                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TXD3                 REG32(IOMUXD_REG_BASE+0x000230C0U) //    4    1     3   3 |                                           |                                          | ADMA.LCDIF.D03                           | CONN.EQOS.RGMII_TXD3                     | LSIO.GPIO0.IO03                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RXC                  REG32(IOMUXD_REG_BASE+0x00023100U) //    4    1     3   4 |                                           |                                          | ADMA.LCDIF.D04                           | CONN.EQOS.RGMII_RXC                      | LSIO.GPIO0.IO04                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RXD3                 REG32(IOMUXD_REG_BASE+0x00023140U) //    4    1     3   5 |                                           |                                          | ADMA.LCDIF.D05                           | CONN.EQOS.RGMII_RXD3                     | LSIO.GPIO0.IO05                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RXD2                 REG32(IOMUXD_REG_BASE+0x00023180U) //    4    1     3   6 |                                           |                                          | ADMA.LCDIF.D06                           | CONN.EQOS.RGMII_RXD2                     | LSIO.GPIO0.IO06                          | LSIO.GPIO6.IO00                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RXD1                 REG32(IOMUXD_REG_BASE+0x000231C0U) //    4    1     3   7 |                                           |                                          | ADMA.LCDIF.D07                           | CONN.EQOS.RGMII_RXD1                     | LSIO.GPIO0.IO07                          | LSIO.GPIO6.IO01                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TXD0                 REG32(IOMUXD_REG_BASE+0x00023200U) //    4    1     3   8 |                                           |                                          | ADMA.LCDIF.D08                           | CONN.EQOS.RGMII_TXD0                     | LSIO.GPIO0.IO08                          | LSIO.GPIO6.IO02                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_TXD1                 REG32(IOMUXD_REG_BASE+0x00023240U) //    4    1     3   9 |                                           |                                          | ADMA.LCDIF.D09                           | CONN.EQOS.RGMII_TXD1                     | LSIO.GPIO0.IO09                          | LSIO.GPIO6.IO03                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RXD0                 REG32(IOMUXD_REG_BASE+0x00023280U) //    4    1     3  10 |  ADMA.SPDIF0.RX                           | ADMA.MQS.R                               | ADMA.LCDIF.D10                           | CONN.EQOS.RGMII_RXD0                     | LSIO.GPIO0.IO10                          | LSIO.GPIO6.IO04                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_RGMII_RX_CTL               REG32(IOMUXD_REG_BASE+0x000232C0U) //    4    1     3  11 |  ADMA.SPDIF0.TX                           | ADMA.MQS.L                               | ADMA.LCDIF.D11                           | CONN.EQOS.RGMII_RX_CTL                   | LSIO.GPIO0.IO11                          | LSIO.GPIO6.IO05                          |                                          |                                          |                                          |
#define IOMUXD__ENET1_REFCLK_125M_25M            REG32(IOMUXD_REG_BASE+0x00023300U) //    4    1     3  12 |  ADMA.SPDIF0.EXT_CLK                      |                                          | ADMA.LCDIF.D12                           | CONN.EQOS.REFCLK_125M_25M                | LSIO.GPIO0.IO12                          | LSIO.GPIO6.IO06                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIORHB REG32(IOMUXD_REG_BASE+0x00023340U) //    4    1     3  13 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SPI3_SCK                         REG32(IOMUXD_REG_BASE+0x00040000U) //    5    2     0   0 |  ADMA.SPI3.SCK                            |                                          | ADMA.LCDIF.D13                           |                                          | LSIO.GPIO0.IO13                          | ADMA.LCDIF.D00                           |                                          |                                          |                                          |
#define IOMUXD__SPI3_SDO                         REG32(IOMUXD_REG_BASE+0x00040040U) //    5    2     0   1 |  ADMA.SPI3.SDO                            |                                          | ADMA.LCDIF.D14                           |                                          | LSIO.GPIO0.IO14                          | ADMA.LCDIF.D01                           |                                          |                                          |                                          |
#define IOMUXD__SPI3_SDI                         REG32(IOMUXD_REG_BASE+0x00040080U) //    5    2     0   2 |  ADMA.SPI3.SDI                            |                                          | ADMA.LCDIF.D15                           |                                          | LSIO.GPIO0.IO15                          | ADMA.LCDIF.D02                           |                                          |                                          |                                          |
#define IOMUXD__SPI3_CS0                         REG32(IOMUXD_REG_BASE+0x000400C0U) //    5    2     0   3 |  ADMA.SPI3.CS0                            | ADMA.ACM.MCLK_OUT1                       | ADMA.LCDIF.HSYNC                         |                                          | LSIO.GPIO0.IO16                          | ADMA.LCDIF.CS                            |                                          |                                          |                                          |
#define IOMUXD__SPI3_CS1                         REG32(IOMUXD_REG_BASE+0x00040100U) //    5    2     0   4 |  ADMA.SPI3.CS1                            | ADMA.I2C3.SCL                            | ADMA.LCDIF.RESET                         | ADMA.SPI2.CS0                            | ADMA.LCDIF.D16                           | ADMA.LCDIF.RD_E                          |                                          |                                          |                                          |
#define IOMUXD__MCLK_IN1                         REG32(IOMUXD_REG_BASE+0x00040140U) //    5    2     0   5 |  ADMA.ACM.MCLK_IN1                        | ADMA.I2C3.SDA                            | ADMA.LCDIF.EN                            | ADMA.SPI2.SCK                            | ADMA.LCDIF.D17                           | ADMA.LCDIF.D03                           |                                          |                                          |                                          |
#define IOMUXD__MCLK_IN0                         REG32(IOMUXD_REG_BASE+0x00040180U) //    5    2     0   6 |  ADMA.ACM.MCLK_IN0                        |                                          | ADMA.LCDIF.VSYNC                         | ADMA.SPI2.SDI                            | LSIO.GPIO0.IO19                          | ADMA.LCDIF.RS                            |                                          |                                          |                                          |
#define IOMUXD__MCLK_OUT0                        REG32(IOMUXD_REG_BASE+0x000401C0U) //    5    2     0   7 |  ADMA.ACM.MCLK_OUT0                       |                                          | ADMA.LCDIF.CLK                           | ADMA.SPI2.SDO                            | LSIO.GPIO0.IO20                          | ADMA.LCDIF.WR_RWN                        |                                          |                                          |                                          |
#define IOMUXD__UART1_TX                         REG32(IOMUXD_REG_BASE+0x00040200U) //    5    2     0   8 |  ADMA.UART1.TX                            | LSIO.PWM0.OUT                            | LSIO.GPT0.CAPTURE                        |                                          | LSIO.GPIO0.IO21                          | ADMA.LCDIF.D04                           |                                          |                                          |                                          |
#define IOMUXD__UART1_RX                         REG32(IOMUXD_REG_BASE+0x00040240U) //    5    2     0   9 |  ADMA.UART1.RX                            | LSIO.PWM1.OUT                            | LSIO.GPT0.COMPARE                        | LSIO.GPT1.CLK                            | LSIO.GPIO0.IO22                          | ADMA.LCDIF.D05                           |                                          |                                          |                                          |
#define IOMUXD__UART1_RTS_B                      REG32(IOMUXD_REG_BASE+0x00040280U) //    5    2     0  10 |  ADMA.UART1.RTS_B                         | LSIO.PWM2.OUT                            | ADMA.LCDIF.D16                           | LSIO.GPT1.CAPTURE                        | LSIO.GPT0.CLK                            | ADMA.LCDIF.D06                           |                                          |                                          |                                          |
#define IOMUXD__UART1_CTS_B                      REG32(IOMUXD_REG_BASE+0x000402C0U) //    5    2     0  11 |  ADMA.UART1.CTS_B                         | LSIO.PWM3.OUT                            | ADMA.LCDIF.D17                           | LSIO.GPT1.COMPARE                        | LSIO.GPIO0.IO24                          | ADMA.LCDIF.D07                           |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIORHK REG32(IOMUXD_REG_BASE+0x00040300U) //    5    2     0  12 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SPI0_SCK                         REG32(IOMUXD_REG_BASE+0x00040340U) //    5    2     0  13 |  ADMA.SPI0.SCK                            | ADMA.SAI0.TXC                            | M40.I2C0.SCL                             | M40.GPIO0.IO00                           | LSIO.GPIO1.IO04                          | ADMA.LCDIF.D08                           |                                          |                                          |                                          |
#define IOMUXD__SPI0_SDI                         REG32(IOMUXD_REG_BASE+0x00040380U) //    5    2     0  14 |  ADMA.SPI0.SDI                            | ADMA.SAI0.TXD                            | M40.TPM0.CH0                             | M40.GPIO0.IO02                           | LSIO.GPIO1.IO05                          | ADMA.LCDIF.D09                           |                                          |                                          |                                          |
#define IOMUXD__SPI0_SDO                         REG32(IOMUXD_REG_BASE+0x000403C0U) //    5    2     0  15 |  ADMA.SPI0.SDO                            | ADMA.SAI0.TXFS                           | M40.I2C0.SDA                             | M40.GPIO0.IO01                           | LSIO.GPIO1.IO06                          | ADMA.LCDIF.D10                           |                                          |                                          |                                          |
#define IOMUXD__SPI0_CS1                         REG32(IOMUXD_REG_BASE+0x00041000U) //    6    2     1   0 |  ADMA.SPI0.CS1                            | ADMA.SAI0.RXC                            | ADMA.SAI1.TXD                            | ADMA.LCD_PWM0.OUT                        | LSIO.GPIO1.IO07                          | ADMA.LCDIF.D11                           |                                          |                                          |                                          |
#define IOMUXD__SPI0_CS0                         REG32(IOMUXD_REG_BASE+0x00041040U) //    6    2     1   1 |  ADMA.SPI0.CS0                            | ADMA.SAI0.RXD                            | M40.TPM0.CH1                             | M40.GPIO0.IO03                           | LSIO.GPIO1.IO08                          | ADMA.LCDIF.D12                           |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIORHT REG32(IOMUXD_REG_BASE+0x00041080U) //    6    2     1   2 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__ADC_IN1                          REG32(IOMUXD_REG_BASE+0x000410C0U) //    6    2     1   3 |  ADMA.ADC.IN1                             | M40.I2C0.SDA                             | M40.GPIO0.IO01                           | ADMA.I2C0.SDA                            | LSIO.GPIO1.IO09                          | ADMA.LCDIF.D13                           |                                          |                                          |                                          |
#define IOMUXD__ADC_IN0                          REG32(IOMUXD_REG_BASE+0x00041100U) //    6    2     1   4 |  ADMA.ADC.IN0                             | M40.I2C0.SCL                             | M40.GPIO0.IO00                           | ADMA.I2C0.SCL                            | LSIO.GPIO1.IO10                          | ADMA.LCDIF.D14                           |                                          |                                          |                                          |
#define IOMUXD__ADC_IN3                          REG32(IOMUXD_REG_BASE+0x00041140U) //    6    2     1   5 |  ADMA.ADC.IN3                             | M40.UART0.TX                             | M40.GPIO0.IO03                           | ADMA.ACM.MCLK_OUT0                       | LSIO.GPIO1.IO11                          | ADMA.LCDIF.D15                           |                                          |                                          |                                          |
#define IOMUXD__ADC_IN2                          REG32(IOMUXD_REG_BASE+0x00041180U) //    6    2     1   6 |  ADMA.ADC.IN2                             | M40.UART0.RX                             | M40.GPIO0.IO02                           | ADMA.ACM.MCLK_IN0                        | LSIO.GPIO1.IO12                          | ADMA.LCDIF.D16                           |                                          |                                          |                                          |
#define IOMUXD__ADC_IN5                          REG32(IOMUXD_REG_BASE+0x000411C0U) //    6    2     1   7 |  ADMA.ADC.IN5                             | M40.TPM0.CH1                             | M40.GPIO0.IO05                           | ADMA.LCDIF.LCDBUSY                       | LSIO.GPIO1.IO13                          | ADMA.LCDIF.D17                           |                                          |                                          |                                          |
#define IOMUXD__ADC_IN4                          REG32(IOMUXD_REG_BASE+0x00041200U) //    6    2     1   8 |  ADMA.ADC.IN4                             | M40.TPM0.CH0                             | M40.GPIO0.IO04                           | ADMA.LCDIF.LCDRESET                      | LSIO.GPIO1.IO14                          |                                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN0_RX                      REG32(IOMUXD_REG_BASE+0x00041240U) //    6    2     1   9 |  ADMA.FLEXCAN0.RX                         | ADMA.SAI2.RXC                            | ADMA.UART0.RTS_B                         | ADMA.SAI1.TXC                            | LSIO.GPIO1.IO15                          | LSIO.GPIO6.IO08                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN0_TX                      REG32(IOMUXD_REG_BASE+0x00041280U) //    6    2     1  10 |  ADMA.FLEXCAN0.TX                         | ADMA.SAI2.RXD                            | ADMA.UART0.CTS_B                         | ADMA.SAI1.TXFS                           | LSIO.GPIO1.IO16                          | LSIO.GPIO6.IO09                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN1_RX                      REG32(IOMUXD_REG_BASE+0x000412C0U) //    6    2     1  11 |  ADMA.FLEXCAN1.RX                         | ADMA.SAI2.RXFS                           | ADMA.FTM.CH2                             | ADMA.SAI1.TXD                            | LSIO.GPIO1.IO17                          | LSIO.GPIO6.IO10                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN1_TX                      REG32(IOMUXD_REG_BASE+0x00041300U) //    6    2     1  12 |  ADMA.FLEXCAN1.TX                         | ADMA.SAI3.RXC                            | ADMA.DMA0.REQ_IN0                        | ADMA.SAI1.RXD                            | LSIO.GPIO1.IO18                          | LSIO.GPIO6.IO11                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN2_RX                      REG32(IOMUXD_REG_BASE+0x00041340U) //    6    2     1  13 |  ADMA.FLEXCAN2.RX                         | ADMA.SAI3.RXD                            | ADMA.UART3.RX                            | ADMA.SAI1.RXFS                           | LSIO.GPIO1.IO19                          | LSIO.GPIO6.IO12                          |                                          |                                          |                                          |
#define IOMUXD__FLEXCAN2_TX                      REG32(IOMUXD_REG_BASE+0x00041380U) //    6    2     1  14 |  ADMA.FLEXCAN2.TX                         | ADMA.SAI3.RXFS                           | ADMA.UART3.TX                            | ADMA.SAI1.RXC                            | LSIO.GPIO1.IO20                          | LSIO.GPIO6.IO13                          |                                          |                                          |                                          |
#define IOMUXD__UART0_RX                         REG32(IOMUXD_REG_BASE+0x000413C0U) //    6    2     1  15 |  ADMA.UART0.RX                            | ADMA.MQS.R                               | ADMA.FLEXCAN0.RX                         | SCU.UART0.RX                             | LSIO.GPIO1.IO21                          | LSIO.GPIO6.IO14                          |                                          |                                          |                                          |
#define IOMUXD__UART0_TX                         REG32(IOMUXD_REG_BASE+0x00042000U) //    7    2     2   0 |  ADMA.UART0.TX                            | ADMA.MQS.L                               | ADMA.FLEXCAN0.TX                         | SCU.UART0.TX                             | LSIO.GPIO1.IO22                          | LSIO.GPIO6.IO15                          |                                          |                                          |                                          |
#define IOMUXD__UART2_TX                         REG32(IOMUXD_REG_BASE+0x00042040U) //    7    2     2   1 |  ADMA.UART2.TX                            | ADMA.FTM.CH1                             | ADMA.FLEXCAN1.TX                         |                                          | LSIO.GPIO1.IO23                          | LSIO.GPIO6.IO16                          |                                          |                                          |                                          |
#define IOMUXD__UART2_RX                         REG32(IOMUXD_REG_BASE+0x00042080U) //    7    2     2   2 |  ADMA.UART2.RX                            | ADMA.FTM.CH0                             | ADMA.FLEXCAN1.RX                         |                                          | LSIO.GPIO1.IO24                          | LSIO.GPIO6.IO17                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIOLH REG32(IOMUXD_REG_BASE+0x000420C0U) //    7    2     2   3 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__JTAG_TRST_B                      REG32(IOMUXD_REG_BASE+0x00042100U) //    7    2     2   4 |  SCU.JTAG.TRST_B                          | SCU.WDOG0.WDOG_OUT                       |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__PMIC_I2C_SCL                     REG32(IOMUXD_REG_BASE+0x00042140U) //    7    2     2   5 |  SCU.PMIC_I2C.SCL                         | SCU.GPIO0.IOXX_PMIC_A35_ON               |                                          |                                          | LSIO.GPIO2.IO01                          |                                          |                                          |                                          |                                          |
#define IOMUXD__PMIC_I2C_SDA                     REG32(IOMUXD_REG_BASE+0x00042180U) //    7    2     2   6 |  SCU.PMIC_I2C.SDA                         | SCU.GPIO0.IOXX_PMIC_GPU_ON               |                                          |                                          | LSIO.GPIO2.IO02                          |                                          |                                          |                                          |                                          |
#define IOMUXD__PMIC_INT_B                       REG32(IOMUXD_REG_BASE+0x000421C0U) //    7    2     2   7 |  SCU.DSC.PMIC_INT_B                       |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_GPIO0_00                     REG32(IOMUXD_REG_BASE+0x00042200U) //    7    2     2   8 |  SCU.GPIO0.IO00                           | SCU.UART0.RX                             | M40.UART0.RX                             | ADMA.UART3.RX                            | LSIO.GPIO2.IO03                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_GPIO0_01                     REG32(IOMUXD_REG_BASE+0x00042240U) //    7    2     2   9 |  SCU.GPIO0.IO01                           | SCU.UART0.TX                             | M40.UART0.TX                             | ADMA.UART3.TX                            | SCU.WDOG0.WDOG_OUT                       |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_PMIC_STANDBY                 REG32(IOMUXD_REG_BASE+0x00042280U) //    7    2     2  10 |  SCU.DSC.PMIC_STANDBY                     |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_BOOT_MODE1                   REG32(IOMUXD_REG_BASE+0x000422C0U) //    7    2     2  11 |  SCU.DSC.BOOT_MODE1                       |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_BOOT_MODE0                   REG32(IOMUXD_REG_BASE+0x00042300U) //    7    2     2  12 |  SCU.DSC.BOOT_MODE0                       |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SCU_BOOT_MODE2                   REG32(IOMUXD_REG_BASE+0x00042340U) //    7    2     2  13 |  SCU.DSC.BOOT_MODE2                       | SCU.DSC.RTC_CLOCK_OUTPUT_32K             |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_OUT1             REG32(IOMUXD_REG_BASE+0x00060000U) //    8    3     0   0 |                                           |                                          |                                          |                                          | LSIO.GPIO2.IO05_IN                       | LSIO.GPIO6.IO19_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_OUT2             REG32(IOMUXD_REG_BASE+0x00060040U) //    8    3     0   1 |                                           |                                          |                                          |                                          | LSIO.GPIO2.IO06_IN                       | LSIO.GPIO6.IO20_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_OUT3             REG32(IOMUXD_REG_BASE+0x00060080U) //    8    3     0   2 |                                           |                                          | ADMA.SAI2.RXC                            |                                          | LSIO.GPIO2.IO07_IN                       | LSIO.GPIO6.IO21_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_OUT4             REG32(IOMUXD_REG_BASE+0x000600C0U) //    8    3     0   3 |                                           |                                          | ADMA.SAI2.RXD                            |                                          | LSIO.GPIO2.IO08_IN                       | LSIO.GPIO6.IO22_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_IN0              REG32(IOMUXD_REG_BASE+0x00060100U) //    8    3     0   4 |                                           |                                          | ADMA.SAI2.RXFS                           |                                          | LSIO.GPIO2.IO09_IN                       | LSIO.GPIO6.IO23_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_IN1              REG32(IOMUXD_REG_BASE+0x00060140U) //    8    3     0   5 |                                           |                                          | ADMA.SAI3.RXC                            |                                          | LSIO.GPIO2.IO10_IN                       | LSIO.GPIO6.IO24_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_IN2              REG32(IOMUXD_REG_BASE+0x00060180U) //    8    3     0   6 |                                           |                                          | ADMA.SAI3.RXD                            |                                          | LSIO.GPIO2.IO11_IN                       | LSIO.GPIO6.IO25_IN                       |                                          |                                          |                                          |
#define IOMUXD__SNVS_TAMPER_IN3              REG32(IOMUXD_REG_BASE+0x000601C0U) //    8    3     0   7 |                                           |                                          | ADMA.SAI3.RXFS                           |                                          | LSIO.GPIO2.IO12_IN                       | LSIO.GPIO6.IO26_IN                       |                                          |                                          |                                          |
#define IOMUXD__SPI1_SCK                         REG32(IOMUXD_REG_BASE+0x00060200U) //    8    3     0   8 |                                           |                                          | ADMA.I2C2.SDA                            | ADMA.SPI1.SCK                            | LSIO.GPIO3.IO00                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SPI1_SDO                         REG32(IOMUXD_REG_BASE+0x00060240U) //    8    3     0   9 |                                           |                                          | ADMA.I2C2.SCL                            | ADMA.SPI1.SDO                            | LSIO.GPIO3.IO01                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SPI1_SDI                         REG32(IOMUXD_REG_BASE+0x00060280U) //    8    3     0  10 |                                           |                                          | ADMA.I2C3.SCL                            | ADMA.SPI1.SDI                            | LSIO.GPIO3.IO02                          |                                          |                                          |                                          |                                          |
#define IOMUXD__SPI1_CS0                         REG32(IOMUXD_REG_BASE+0x000602C0U) //    8    3     0  11 |                                           |                                          | ADMA.I2C3.SDA                            | ADMA.SPI1.CS0                            | LSIO.GPIO3.IO03                          |                                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_GPIORHD REG32(IOMUXD_REG_BASE+0x00060300U) //    8    3     0  12 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_DATA1                     REG32(IOMUXD_REG_BASE+0x00061000U) //    9    3     1   0 |  LSIO.QSPI0A.DATA1                        |                                          |                                          |                                          | LSIO.GPIO3.IO10                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_DATA0                     REG32(IOMUXD_REG_BASE+0x00061040U) //    9    3     1   1 |  LSIO.QSPI0A.DATA0                        |                                          |                                          |                                          | LSIO.GPIO3.IO09                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_DATA3                     REG32(IOMUXD_REG_BASE+0x00061080U) //    9    3     1   2 |  LSIO.QSPI0A.DATA3                        |                                          |                                          |                                          | LSIO.GPIO3.IO12                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_DATA2                     REG32(IOMUXD_REG_BASE+0x000610C0U) //    9    3     1   3 |  LSIO.QSPI0A.DATA2                        |                                          |                                          |                                          | LSIO.GPIO3.IO11                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_SS0_B                     REG32(IOMUXD_REG_BASE+0x00061100U) //    9    3     1   4 |  LSIO.QSPI0A.SS0_B                        |                                          |                                          |                                          | LSIO.GPIO3.IO14                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_DQS                       REG32(IOMUXD_REG_BASE+0x00061140U) //    9    3     1   5 |  LSIO.QSPI0A.DQS                          |                                          |                                          |                                          | LSIO.GPIO3.IO13                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0A_SCLK                      REG32(IOMUXD_REG_BASE+0x00061180U) //    9    3     1   6 |  LSIO.QSPI0A.SCLK                         |                                          |                                          |                                          | LSIO.GPIO3.IO16                          |                                          |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_QSPI0A REG32(IOMUXD_REG_BASE+0x000611C0U) //    9    3     1   7 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_SCLK                      REG32(IOMUXD_REG_BASE+0x00061200U) //    9    3     1   8 |  LSIO.QSPI0B.SCLK                         |                                          |                                          |                                          | LSIO.GPIO3.IO17                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_DQS                       REG32(IOMUXD_REG_BASE+0x00061240U) //    9    3     1   9 |  LSIO.QSPI0B.DQS                          |                                          |                                          |                                          | LSIO.GPIO3.IO22                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_DATA1                     REG32(IOMUXD_REG_BASE+0x00061280U) //    9    3     1  10 |  LSIO.QSPI0B.DATA1                        |                                          |                                          |                                          | LSIO.GPIO3.IO19                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_DATA0                     REG32(IOMUXD_REG_BASE+0x000612C0U) //    9    3     1  11 |  LSIO.QSPI0B.DATA0                        |                                          |                                          |                                          | LSIO.GPIO3.IO18                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_DATA3                     REG32(IOMUXD_REG_BASE+0x00061300U) //    9    3     1  12 |  LSIO.QSPI0B.DATA3                        |                                          |                                          |                                          | LSIO.GPIO3.IO21                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_DATA2                     REG32(IOMUXD_REG_BASE+0x00061340U) //    9    3     1  13 |  LSIO.QSPI0B.DATA2                        |                                          |                                          |                                          | LSIO.GPIO3.IO20                          |                                          |                                          |                                          |                                          |
#define IOMUXD__QSPI0B_SS0_B                     REG32(IOMUXD_REG_BASE+0x00061380U) //    9    3     1  14 |  LSIO.QSPI0B.SS0_B                        |                                          |                                          |                                          | LSIO.GPIO3.IO23                          | LSIO.QSPI0A.SS1_B                        |                                          |                                          |                                          |
#define IOMUXD__IOMUXD_COMP_CTL_GPIO_1V8_3V3_QSPI0B REG32(IOMUXD_REG_BASE+0x000613C0U) //    9    3     1  15 |                                           |                                          |                                          |                                          |                                          |                                          |                                          |                                          |                                          |

// GROUP REGISTERS FOR WAKEUP CONTROL
#define IOMUXD__GROUP_0_0                        REG32(IOMUXD_REG_BASE+0x00000400U) //    0    0     0   0 |          
#define IOMUXD__GROUP_1_0                        REG32(IOMUXD_REG_BASE+0x00020400U) //    1    1     0   0 |          
#define IOMUXD__GROUP_1_1                        REG32(IOMUXD_REG_BASE+0x00021400U) //    2    1     1   0 |          
#define IOMUXD__GROUP_1_2                        REG32(IOMUXD_REG_BASE+0x00022400U) //    3    1     2   0 |          
#define IOMUXD__GROUP_1_3                        REG32(IOMUXD_REG_BASE+0x00023400U) //    4    1     3   0 |          
#define IOMUXD__GROUP_2_0                        REG32(IOMUXD_REG_BASE+0x00040400U) //    5    2     0   0 |          
#define IOMUXD__GROUP_2_1                        REG32(IOMUXD_REG_BASE+0x00041400U) //    6    2     1   0 |          
#define IOMUXD__GROUP_2_2                        REG32(IOMUXD_REG_BASE+0x00042400U) //    7    2     2   0 |          
#define IOMUXD__GROUP_3_0                        REG32(IOMUXD_REG_BASE+0x00060400U) //    8    3     0   0 |          
#define IOMUXD__GROUP_3_1                        REG32(IOMUXD_REG_BASE+0x00061400U) //    9    3     1   0 |          

#endif
