/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the LSIO subsystem.
 *
 * @addtogroup LSIO_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/rsrc_ss_h.pl */

#ifndef SC_SS_LSIO_RSRC_H
#define SC_SS_LSIO_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/** @{ */
#define SS_R_PWM_0               0U
#define SS_R_PWM_1               1U
#define SS_R_PWM_2               2U
#define SS_R_PWM_3               3U
#define SS_R_PWM_4               4U
#define SS_R_PWM_5               5U
#define SS_R_PWM_6               6U
#define SS_R_PWM_7               7U
#define SS_R_GPIO_0              8U
#define SS_R_GPIO_1              9U
#define SS_R_GPIO_2              10U
#define SS_R_GPIO_3              11U
#define SS_R_GPIO_4              12U
#define SS_R_GPIO_5              13U
#define SS_R_GPIO_6              14U
#define SS_R_GPIO_7              15U
#define SS_R_FSPI_0              16U
#define SS_R_FSPI_1              17U
#define SS_R_GPT_0               18U
#define SS_R_GPT_1               19U
#define SS_R_GPT_2               20U
#define SS_R_GPT_3               21U
#define SS_R_GPT_4               22U
#define SS_R_KPP                 23U
#define SS_R_MU_0A               24U
#define SS_R_MU_1A               25U
#define SS_R_MU_2A               26U
#define SS_R_MU_3A               27U
#define SS_R_MU_4A               28U
#define SS_R_MU_5A               29U
#define SS_R_MU_6A               30U
#define SS_R_MU_7A               31U
#define SS_R_MU_8A               32U
#define SS_R_MU_9A               33U
#define SS_R_MU_10A              34U
#define SS_R_MU_11A              35U
#define SS_R_MU_12A              36U
#define SS_R_MU_13A              37U
#define SS_R_MU_5B               38U
#define SS_R_MU_6B               39U
#define SS_R_MU_7B               40U
#define SS_R_MU_8B               41U
#define SS_R_MU_9B               42U
#define SS_R_MU_10B              43U
#define SS_R_MU_11B              44U
#define SS_R_MU_12B              45U
#define SS_R_MU_13B              46U
#define SS_R_IEE                 47U
#define SS_R_IEE_R0              48U
#define SS_R_IEE_R1              49U
#define SS_R_IEE_R2              50U
#define SS_R_IEE_R3              51U
#define SS_R_IEE_R4              52U
#define SS_R_IEE_R5              53U
#define SS_R_IEE_R6              54U
#define SS_R_IEE_R7              55U
#define SS_R_OCRAM               56U
/** @} */

#endif /* SC_SS_LSIO_RSRC_H */

/** @} */

