
OBJS += $(OUT)/ss/hsio/v2/ss.o

CONFIGH += $(SRC)/ss/hsio/v2/config.h $(SRC)/ss/hsio/v2/rsrc.h

RSRC_MD += $(SRC)/ss/hsio/v2/resource.txt

CLK_MD += $(SRC)/ss/hsio/v2/clock.txt

CTRL_MD += $(SRC)/ss/hsio/v2/control.txt

DIRS += $(OUT)/ss/hsio/v2

