
OBJS += $(OUT)/svc/pad/svc.o

RPCS += $(OUT)/svc/pad/rpc_srv.o

RPCL += $(OUT)/svc/pad/rpc_clnt.o

RPCH += $(SRC)/svc/pad/rpc.h

RPCC += $(SRC)/svc/pad/rpc_srv.c		 \
		$(SRC)/svc/pad/rpc_clnt.c        \
		$(SRC)/svc/pad/rpc_xlate.c

RPCHDR += $(SRC)/svc/pad/rpc_header.h

DIRS += $(OUT)/svc/pad

