
OBJS += $(OUT)/ss/a53/v1/ss.o

CONFIGH += $(SRC)/ss/a53/v1/config.h $(SRC)/ss/a53/v1/rsrc.h

RSRC_MD += $(SRC)/ss/a53/v1/resource.txt

CLK_MD += $(SRC)/ss/a53/v1/clock.txt

CTRL_MD += $(SRC)/ss/a53/v1/control.txt

DIRS += $(OUT)/ss/a53/v1

