
# Local settings
LLC := qx
LUC := QX
LOPT := -DHAS_SECO
LSOFF := 0x32060000

# Determine configs
ifeq ($(MAKECMDGOALS), $(LLC))
    CONFIG := mx8$(LLC)
    DEVICE := MX8$(LUC)
    OUT := build_mx8$(LLC)
    HW := REAL
    OPT := $(LOPT)
    SREC_OFFSET := $(LSOFF)
	LC := $(LLC)
	UC := $(LUC)
	DEF_B := val
	TEST_B := mek
    ifneq ($(UPPER_R),B0)
    ifneq ($(UPPER_R),C0)
    $(error Invalid revision)
	endif
    endif
endif
ifeq ($(MAKECMDGOALS), clean-obj-$(LLC))
    CONFIG := mx8$(LLC)
    DEVICE := MX8$(LUC)
    OUT := build_mx8$(LLC)
    HW := SIMU
	LC := $(LLC)
	UC := $(LUC)
endif

#Help text
HELP += \
	"\t$(LLC)             : build for i.MX8$(LUC) die, output in build_mx8$(LLC)\n"

