/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the IMG subsystem.
 *
 * @addtogroup IMG_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/rsrc_ss_h.pl */

#ifndef SC_SS_IMG_RSRC_H
#define SC_SS_IMG_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/** @{ */
#define SS_R_ISI_CH0             0U
#define SS_R_ISI_CH1             1U
#define SS_R_ISI_CH2             2U
#define SS_R_ISI_CH3             3U
#define SS_R_ISI_CH4             4U
#define SS_R_ISI_CH5             5U
#define SS_R_ISI_CH6             6U
#define SS_R_ISI_CH7             7U
#define SS_R_MJPEG_DEC_MP        8U
#define SS_R_MJPEG_DEC_S0        9U
#define SS_R_MJPEG_DEC_S1        10U
#define SS_R_MJPEG_DEC_S2        11U
#define SS_R_MJPEG_DEC_S3        12U
#define SS_R_MJPEG_ENC_MP        13U
#define SS_R_MJPEG_ENC_S0        14U
#define SS_R_MJPEG_ENC_S1        15U
#define SS_R_MJPEG_ENC_S2        16U
#define SS_R_MJPEG_ENC_S3        17U
/** @} */

#endif /* SC_SS_IMG_RSRC_H */

/** @} */

