
OBJS += $(OUT)/svc/seco/svc.o

RPCS += $(OUT)/svc/seco/rpc_srv.o

RPCL += $(OUT)/svc/seco/rpc_clnt.o

RPCH += $(SRC)/svc/seco/rpc.h

RPCC += $(SRC)/svc/seco/rpc_srv.c		 \
		$(SRC)/svc/seco/rpc_clnt.c       \
		$(SRC)/svc/seco/rpc_xlate.c

RPCHDR += $(SRC)/svc/seco/rpc_header.h

DIRS += $(OUT)/svc/seco

