/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the HSIO subsystem.
 *
 * @addtogroup HSIO_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/rsrc_ss_h.pl */

#ifndef SC_SS_HSIO_RSRC_H
#define SC_SS_HSIO_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/** @{ */
#define SS_R_PCIE_A              0U
#define SS_R_PCIE_B              1U
#define SS_R_SATA_0              2U
#define SS_R_SERDES_0            3U
#define SS_R_SERDES_1            4U
#define SS_R_HSIO_GPIO           5U
#define SS_R_MATCH_0             6U
#define SS_R_MATCH_1             7U
#define SS_R_MATCH_2             8U
#define SS_R_MATCH_3             9U
#define SS_R_MATCH_4             10U
#define SS_R_MATCH_5             11U
#define SS_R_MATCH_6             12U
#define SS_R_MATCH_7             13U
#define SS_R_MATCH_8             14U
#define SS_R_MATCH_9             15U
#define SS_R_MATCH_10            16U
#define SS_R_MATCH_11            17U
#define SS_R_MATCH_12            18U
#define SS_R_MATCH_13            19U
#define SS_R_MATCH_14            20U
#define SS_R_MATCH_15            21U
#define SS_R_MATCH_16            22U
#define SS_R_MATCH_17            23U
#define SS_R_MATCH_18            24U
#define SS_R_MATCH_19            25U
#define SS_R_MATCH_20            26U
#define SS_R_MATCH_21            27U
#define SS_R_MATCH_22            28U
#define SS_R_MATCH_23            29U
#define SS_R_MATCH_24            30U
#define SS_R_MATCH_25            31U
#define SS_R_MATCH_26            32U
#define SS_R_MATCH_27            33U
#define SS_R_MATCH_28            34U
/** @} */

#endif /* SC_SS_HSIO_RSRC_H */

/** @} */

