/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the M4 subsystem.
 *
 * @addtogroup M4_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/rsrc_ss_h.pl */

#ifndef SC_SS_M4_RSRC_H
#define SC_SS_M4_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/** @{ */
#define SS_R_M4_0_PID0           0U
#define SS_R_M4_0_PID1           1U
#define SS_R_M4_0_PID2           2U
#define SS_R_M4_0_PID3           3U
#define SS_R_M4_0_PID4           4U
#define SS_R_M4_0_RGPIO          5U
#define SS_R_M4_0_SEMA42         6U
#define SS_R_M4_0_TPM            7U
#define SS_R_M4_0_PIT            8U
#define SS_R_M4_0_UART           9U
#define SS_R_M4_0_I2C            10U
#define SS_R_M4_0_INTMUX         11U
#define SS_R_M4_0_MU_0B          12U
#define SS_R_M4_0_MU_0A0         13U
#define SS_R_M4_0_MU_0A1         14U
#define SS_R_M4_0_MU_0A2         15U
#define SS_R_M4_0_MU_0A3         16U
#define SS_R_M4_0_MU_1A          17U
#define SS_R_M4_1_PID0           0U
#define SS_R_M4_1_PID1           1U
#define SS_R_M4_1_PID2           2U
#define SS_R_M4_1_PID3           3U
#define SS_R_M4_1_PID4           4U
#define SS_R_M4_1_RGPIO          5U
#define SS_R_M4_1_SEMA42         6U
#define SS_R_M4_1_TPM            7U
#define SS_R_M4_1_PIT            8U
#define SS_R_M4_1_UART           9U
#define SS_R_M4_1_I2C            10U
#define SS_R_M4_1_INTMUX         11U
#define SS_R_M4_1_MU_0B          12U
#define SS_R_M4_1_MU_0A0         13U
#define SS_R_M4_1_MU_0A1         14U
#define SS_R_M4_1_MU_0A2         15U
#define SS_R_M4_1_MU_0A3         16U
#define SS_R_M4_1_MU_1A          17U
/** @} */

#endif /* SC_SS_M4_RSRC_H */

/** @} */

